<a href="https://colab.research.google.com/github/Rafaelsantosz2004/Projeto-de-Analise-de-Dados-/blob/main/Projeto_Policia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Importando a Biblioteca e a Base de Dados**

In [ ]:
import pandas as pd

In [ ]:
police_pd = pd.read_csv("police.csv")
display(police_pd)

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,2005-01-18,08:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,2005-01-23,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2005-02-20,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91736,2015-12-31,20:27,NaN,M,1986.0,29.0,White,Speeding,Speeding,False,NaN,Warning,False,0-15 Min,False
91737,2015-12-31,20:35,NaN,F,1982.0,33.0,White,Equipment/Inspection Violation,Equipment,False,NaN,Warning,False,0-15 Min,False
91738,2015-12-31,20:45,NaN,M,1992.0,23.0,White,Other Traffic Violation,Moving violation,False,NaN,Warning,False,0-15 Min,False
91739,2015-12-31,21:42,NaN,M,1993.0,22.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
91740,2015-12-31,22:46,NaN,M,1959.0,56.0,Hispanic,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

# **ETL da Base de Dados**

In [ ]:
police_pd = police_pd.dropna(how='all', axis=1)
display(police_pd)

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,2005-01-18,08:15,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,2005-01-23,23:15,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2005-02-20,17:15,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91736,2015-12-31,20:27,M,1986.0,29.0,White,Speeding,Speeding,False,NaN,Warning,False,0-15 Min,False
91737,2015-12-31,20:35,F,1982.0,33.0,White,Equipment/Inspection Violation,Equipment,False,NaN,Warning,False,0-15 Min,False
91738,2015-12-31,20:45,M,1992.0,23.0,White,Other Traffic Violation,Moving violation,False,NaN,Warning,False,0-15 Min,False
91739,2015-12-31,21:42,M,1993.0,22.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
91740,2015-12-31,22:46,M,1959.0,56.0,Hispanic,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [ ]:
police_pd = police_pd.dropna()
display(police_pd)

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
24,2005-08-28,01:00,M,1979.0,26.0,White,Other Traffic Violation,Moving violation,True,"Incident to Arrest,Protective Frisk",Arrest Driver,True,16-30 Min,False
40,2005-10-01,00:00,M,1988.0,17.0,White,Equipment/Inspection Violation,Equipment,True,Probable Cause,Arrest Driver,True,16-30 Min,True
41,2005-10-01,00:00,M,1988.0,17.0,White,Equipment/Inspection Violation,Equipment,True,Probable Cause,Citation,False,30+ Min,True
80,2005-10-02,09:30,M,1975.0,30.0,White,Speeding,Speeding,True,Incident to Arrest,Arrest Driver,True,30+ Min,False
106,2005-10-03,14:00,M,1978.0,27.0,Black,Equipment/Inspection Violation,Equipment,True,Probable Cause,Citation,False,16-30 Min,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91494,2015-12-18,09:30,M,1966.0,49.0,White,Registration Violation,Registration/plates,True,Incident to Arrest,No Action,False,16-30 Min,False
91548,2015-12-21,01:39,M,1986.0,29.0,White,Other Traffic Violation,Moving violation,True,Incident to Arrest,Citation,False,0-15 Min,False
91672,2015-12-28,11:05,F,1996.0,19.0,White,APB,Other,True,Incident to Arrest,Citation,False,16-30 Min,True
91700,2015-12-30,08:51,F,1987.0,28.0,Hispanic,Speeding,Speeding,True,"Probable Cause,Reasonable Suspicion",Citation,False,30+ Min,True
91708,2015-12-30,13:15,M,1992.0,23.0,White,Seatbelt Violation,Seat belt,True,Incident to Arrest,Arrest Passenger,True,16-30 Min,False

In [ ]:

contagem = police_pd['violation_raw'].value_counts()

police_pd['quantidade'] = police_pd['violation_raw'].map(contagem)

total = len(police_pd)

police_pd['percentual'] = (police_pd['quantidade'] / total) * 100

display(police_pd)

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,quantidade,percentual
24,2005-08-28,01:00,M,1979.0,26.0,White,Other Traffic Violation,Moving violation,True,"Incident to Arrest,Protective Frisk",Arrest Driver,True,16-30 Min,False,895,28.030066
40,2005-10-01,00:00,M,1988.0,17.0,White,Equipment/Inspection Violation,Equipment,True,Probable Cause,Arrest Driver,True,16-30 Min,True,704,22.048231
41,2005-10-01,00:00,M,1988.0,17.0,White,Equipment/Inspection Violation,Equipment,True,Probable Cause,Citation,False,30+ Min,True,704,22.048231
80,2005-10-02,09:30,M,1975.0,30.0,White,Speeding,Speeding,True,Incident to Arrest,Arrest Driver,True,30+ Min,False,956,29.940495
106,2005-10-03,14:00,M,1978.0,27.0,Black,Equipment/Inspection Violation,Equipment,True,Probable Cause,Citation,False,16-30 Min,False,704,22.048231
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91494,2015-12-18,09:30,M,1966.0,49.0,White,Registration Violation,Registration/plates,True,Incident to Arrest,No Action,False,16-30 Min,False,333,10.429064
91548,2015-12-21,01:39,M,1986.0,29.0,White,Other Traffic Violation,Moving violation,True,Incident to Arrest,Citation,False,0-15 Min,False,895,28.030066
91672,2015-12-28,11:05,F,1996.0,19.0,White,APB,Other,True,Incident to Arrest,Citation,False,16-30 Min,True,20,0.626370
91700,2015-12-30,08:51,F,1987.0,28.0,Hispanic,Speeding,Speeding,True,"Probable Cause,Reasonable Suspicion",Citation,False,30+ Min,True,956,29.940495
91708,2015-12-30,13:15,M,1992.0,23.0,White,Seatbelt Violation,Seat belt,True,Incident to Arrest,Arrest Passenger,True,16-30 Min,False,96,3.006577

In [ ]:
police_pd['driver_age_raw'] = police_pd['driver_age_raw'].astype(int)

In [ ]:
police_pd.to_csv("police_tratado.csv", index=False)

In [ ]:
from google.colab import files

files.download("police_tratado.csv")